layout_spectrum: 0.717842719654027
typography_spectrum: 0.8621382268117095
color:
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
  brandStrength: 0.9593401018391815
  lightness: 0.7506339575007263
  saturation: 0.592365648287745
  rhythmicContrast: 0.9247498351368721
github: true
author:
  name: Tous droits réservé lunnagraphics.ca Ani Markarian
  email: lunnagraphics@gmail.com
  url: 'https://thegrid.ai/55978/lunnagraphics'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a961e9f3-034c-4f17-877c-97695091663d.png
name: ' '
url: 'https://thegrid.ai/55978/lunnagraphics'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Portfolio
    id: 41472860-b103-4a37-b83c-589b30dc8bd4
    type: content
  - name: Politique
    url: 'https://lunnagraphics.weebly.com/policy-669152.html'
    type: external
title: Lunnagraphics.ca
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/a2b898f0-7f90-4ef9-9804-e47b0adfef0f.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/a2b898f0-7f90-4ef9-9804-e47b0adfef0f.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/b7e37133-37c2-4e9e-9b02-579d9347f003.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/b7e37133-37c2-4e9e-9b02-579d9347f003.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/4ec9a982-96ed-42ce-82d7-85bd501e48fc.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/4ec9a982-96ed-42ce-82d7-85bd501e48fc.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: ''
purpose:
  - type: internal
    label: Fr
    item: 16b62d41-e606-4613-8653-e8e28c954e94
  - type: internal
    label: English
    item: 1031b6c1-2535-4cc1-b09a-6ff8dfa0b79a
