layout_spectrum: 0.7197658223366493
typography_spectrum: 0.9600382318751572
color:
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
  brandStrength: 0.8638934890203879
  lightness: 0.25724609000239484
  saturation: 0.1889771997225056
  rhythmicContrast: 0.7548483274093285
github: true
author:
  name: Tous droits réservé lunnagraphics.ca Ani Markarian
  email: lunnagraphics@gmail.com
  url: 'https://thegrid.ai/55978/lunnagraphics'
logo: null
name: ' '
url: 'https://thegrid.ai/55978/lunnagraphics'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: A Propos
    id: 41472860-b103-4a37-b83c-589b30dc8bd4
    type: content
  - name: Politique
    url: 'https://lunnagraphics.weebly.com/policy-669152.html'
    type: external
title: Lunnagraphics.ca
content: []
description: ''
