layout_spectrum: 0.015260089806529997
typography_spectrum: 0.7037951054037687
color:
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
  brandStrength: 0.10987741893553868
  lightness: 0.8316105932501688
  saturation: 0.9698074705150938
  rhythmicContrast: 0.6909595749687661
github: true
author:
  name: Tous droits réservé lunnagraphics.ca Ani Markarian
  email: lunnagraphics@gmail.com
  url: 'https://thegrid.ai/55978/lunnagraphics'
logo: null
name: ' '
url: 'https://thegrid.ai/55978/lunnagraphics'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Lunnagraphics.ca
    url: 'https://lunnagraphics.weebly.com/fr.html'
    type: external
  - name: Portfolio
    url: 'https://lunnagraphics.weebly.com/portfolio-409683.html'
    type: external
  - name: Politique
    url: 'https://lunnagraphics.weebly.com/policy-669152.html'
    type: external
title: Lunnagraphics.ca
content: []
description: ''
