typography_spectrum: 0.8231023645141889
color:
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
  brandStrength: 0.4359481376486987
  lightness: 0.7341067805671418
  saturation: 0.6998119171469998
  rhythmicContrast: 0.8611191256367371
github: true
layout_spectrum: 0.32334148307672084
author:
  name: Tous droits réservé lunnagraphics.ca Ani Markarian
  email: lunnagraphics@gmail.com
  url: 'https://thegrid.ai/55978/lunnagraphics'
logo: null
name: ' '
url: 'https://thegrid.ai/55978/lunnagraphics'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Lunnagraphics.ca
    url: 'https://lunnagraphics.weebly.com/fr.html'
    type: external
  - name: A Propos
    id: 41472860-b103-4a37-b83c-589b30dc8bd4
    type: content
  - name: Portfolio
    url: 'https://lunnagraphics.weebly.com/portfolio-409683.html'
    type: external
  - name: Politique
    url: 'https://lunnagraphics.weebly.com/policy-669152.html'
    type: external
title: Lunnagraphics.ca
content: []
description: ''
