layout_spectrum: 0.09001394139409138
typography_spectrum: 0.3264720594241182
color:
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
  brandStrength: 0.7879716977981464
  lightness: 0.7158875690366482
  saturation: 0.46440388501133073
  rhythmicContrast: 0.4811804629587522
github: true
author:
  name: Ani Markarian
  email: lunnagraphics@gmail.com
  url: 'https://thegrid.ai/55978/lunnagraphics'
logo: null
name: ' '
url: 'https://thegrid.ai/55978/lunnagraphics'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Lunnagraphics.ca
    url: 'https://lunnagraphics.weebly.com/fr.html'
    type: external
  - name: Portfolio
    url: 'https://lunnagraphics.weebly.com/portfolio-409683.html'
    type: external
  - name: Politique
    url: 'https://lunnagraphics.weebly.com/policy-669152.html'
    type: external
title: Lunnagraphics.ca
content: []
description: ''
